### ISSUE TITLE
Possible issue with processed data

### ISSUE THREAD

**Issue by ConnectedSystems** [oi-analytics/oi-risk-vis#8]
Hello again

Thanks again for your help the other day.
We've run into a separate issue with the data downloaded from the Azure blob storage.

We are not sure if all files were processed correctly, especially the flood risk scenarios.
I've attached (below) an example set of files to showcase what we're seeing with Risks / PHL / Fluvial flood data

The historic dataset shows 171 rows when loaded into QGIS.

The rcp45 dataset has a count of 240 rows, but only 13 displayed, with the rest filtered out; it seems only those 13 items are displayable and exportable. I've included a screenshot of what I'm seeing below as well.

We initially thought it was a filter for non-zero rows, but loading the mid files as CSV shows otherwise: all rows have data and should be displayed.

We're wondering if you had any insights on how to clear the filtering (as reported in QGIS) to enable exporting the full range of data.

We are running format conversion using a script [I wrote](https://github.com/ConnectedSystems/rdl-mid-to-gpkg) - it uses geopandas so hits the same issue as QGIS in exporting the data. I'm wondering if you have any insights on how to clear that filter to enable exporting the full range of data.

Thank you

Zip of example files
[demo_issue.zip](https://github.com/oi-analytics/oi-risk-vis/files/6608668/demo_issue.zip)

Screenshot of attribute table in QGIS 

![data_filtered](https://user-images.githubusercontent.com/4075136/121013520-420fdb00-c7dc-11eb-9bc6-d982587194ad.png)

**Comment by tomalrussell** [comment]
Hi @ConnectedSystems - this is due to the unusually large number of columns in these files, and the fact they were written directly from the C++ analysis code.

The GDAL MID reader defines a maximum of 10,000 characters per line: https://github.com/OSGeo/gdal/blob/fec15b146f8a750c23c5e765cac12ed5fc9c2b85/gdal/ogr/ogrsf_frmts/mitab/mitab_priv.h#L1910 

This affects geopandas, fiona, ogr2ogr, and QGIS in the same way.

To demonstrate with ogr2ogr:
```bash
$ ogr2ogr -f "GPKG" PHL_fluvial_rcp4p5.gpkg PHL_fluvial_rcp4p5.mid 
# ... emits warnings about field name lengths, then fails with errors:
Warning 1: No SRS set on layer. Assuming it is long/lat on WGS84 ellipsoid
ERROR 1: Maximum number of characters allowed reached.
ERROR 3: Unexpected EOF while reading attribute record from MID file.
ERROR 6: Error during reading Record.
ERROR 1: Terminating translation prematurely after failed
translation of layer PHL_fluvial_rcp4p5 (use -skipfailures to skip errors)

ogrinfo -ro PHL_fluvial_rcp4p5.mid PHL_fluvial_rcp4p5
# ... emits data for first 13 features, then fails with errors
ERROR 3: Unexpected EOF while reading attribute record from MID file.
ERROR 6: Error during reading Record.

cat PHL_fluvial_rcp4p5.mid | awk '{print length}' | head -n15
# ... check line length first 15 lines
4830
4866
4817
8195
2946
2967
2960
2964
2852
2850
2849
2847
3430
10370
3431
```

A couple of ideas:

You could write a small MIF/MID reader along the lines of what's in https://github.com/oi-analytics/seasia/blob/main/analysis/oia_risk_model/mif.h (if you focus on reading and parsing, ignore the analysis bits for this) - or some other way to reduce the number of columns and line length before passing to GDAL.

Or try building GDAL with CXX_FLAGS "-DMIDMAXCHAR=15000" (the longest line in the example above is 12,002), and persuade QGIS or python to use your built version.

**Comment by ConnectedSystems** [comment]
Thanks again @tomalrussell very comprehensive and very much appreciated!

**Comment by ConnectedSystems** [comment]
Once again, thank you @tomalrussell - we're now able to convert these to geopackage correctly.
